# Generated by Django 5.2.8 on 2026-07-21 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('exchange', models.CharField(choices=[('US', 'US (NYSE/NASDAQ)'), ('NSE', 'NSE (India)'), ('BSE', 'BSE (India)')], default='US', max_length=5)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'symbol', 'exchange')},
            },
        ),
    ]
